# Generated by Django 2.1.7 on 2019-03-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images')),
                ('gender', models.CharField(choices=[('male', '수컷'), ('female', '암컷'), ('null', '모름')], max_length=20)),
                ('habitat_x', models.FloatField()),
                ('habitat_y', models.FloatField()),
                ('body', models.TextField()),
                ('lasteat', models.DateTimeField()),
            ],
        ),
    ]
