# Generated by Django 2.1.7 on 2019-03-02 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('cat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='postapp.Cat')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postapp.Vote'),
        ),
    ]
