# Generated by Django 2.1.7 on 2019-03-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_auto_20190302_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='voting',
            field=models.BooleanField(default=False),
        ),
    ]
