# Generated by Django 2.1.7 on 2019-03-02 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0003_vote_voting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='lasteat',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 7, 38, 38, 328694)),
        ),
    ]
