# Generated by Django 2.1.7 on 2019-03-02 07:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0004_auto_20190302_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 7, 39, 23, 711315, tzinfo=utc)),
        ),
    ]
