# Generated by Django 2.1.7 on 2019-03-02 07:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0006_auto_20190302_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 2, 7, 40, 47, 424573, tzinfo=utc)),
        ),
    ]
