# Generated by Django 2.1.7 on 2019-03-02 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0007_auto_20190302_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
