# Generated by Django 2.1.7 on 2019-04-07 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0012_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postapp.Cat')),
            ],
        ),
    ]
