# Generated by Django 2.1.7 on 2019-04-07 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0013_catimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catimage',
            old_name='image',
            new_name='sub_image',
        ),
    ]
